### ISSUE TITLE
Can't launch webui

### ISSUE THREAD

**Issue by lutticoelho** [Sharrnah/stable-diffusion-docker#2]
For some reason when I try to run the docker-compose with the pre built image the webui isn't working. Logs  and configuration bellow. Any ideas how to solve it?

---
**.wslconfig**
[wsl2]
memory=13GB 
processors=3
localhostForwarding=true
----
**environment:**
      - RUN_MODE=OPTIMIZED
      - WEBUI_RELAUNCH=true
      - ENABLE_TEXTUAL_INVERSION
----
**Host config** 
GPU: NVIDIA GeForce 940MX
Memory: 16GB
winver: 21H2 - 19044.255.1
WSL ver:  Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Mar 2 00:30:59 UTC 2022
----
**Logs:**
Found GFPGAN
Found RealESRGAN
Found LDSR
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Traceback (most recent call last):
  File "scripts/webui.py", line 451, in <module>
    model,modelCS,modelFS,device, config = load_SD_model()
  File "scripts/webui.py", line 399, in load_SD_model
    sd = load_sd_from_config(opt.ckpt)
  File "scripts/webui.py", line 165, in load_sd_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
ERROR conda.cli.main_run:execute(41): `conda run python -u scripts/webui.py --gfpgan-cpu --esrgan-cpu --optimized` failed. (See above for error)
entrypoint.sh: Process is ending. Relaunching in 0.5s...
entrypoint.sh: Launching with arguments --gfpgan-cpu --esrgan-cpu --optimized

Relaunch count: 9

**Comment by Sharrnah** [comment]
That sounds like it could not load the model.ckpt.
And it seems the old download link where it downloaded it does no longer work.


i would recommend a newer project anyway, since a lot has changed since i last updated this.
for example https://github.com/AbdBarho/stable-diffusion-webui-docker looks great.

Sorry for the trouble. I will probably archive this repository.

**Comment by lutticoelho** [comment]
No problem, your repo was the first one I found with a link for how to use NVIDIA driver with docker. So you already helped me. 
Thank you. I'll look for other projects.

**Comment by Sharrnah** [comment]
i might come to it later and update this repo to use a newer UI. probably [AUTOMATIC1111](https://github.com/AUTOMATIC1111) since it is the most feature rich. But until then i close this issue and this repo now.
